version: '3'

services:
  store:
    image: modelyz:latest
    build:
      context: .
      args:
        - WSS=${WSS}
    command: /srv/store/store -h store
    ports:
      - "8081:8081"
    volumes:
      - store:/srv/store/data

  studio:
    image: modelyz:latest
    build:
      context: .
      args:
        - WSS=${WSS}
    command: /srv/studio/studio -d studio -f studio/data/messagestore.txt --store_host store
    depends_on:
      - store
    ports:
      - "8080:8080"
    volumes:
      - studio:/srv/studio/data

  ident:
    image: modelyz:latest
    build:
      context: .
      args:
        - WSS=${WSS}
    command: /srv/ident/ident --store_host store
    depends_on:
      - store
    volumes:
      - ident:/srv/ident/data

volumes:
  store:
  studio:
  ident:
